<a href="https://colab.research.google.com/github/curiousbasil/DockerFlaskSQLAlchemy/blob/master/Array_Assignment_IS_6651J2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


# NumPy Exercises - Faisal Sukkar


## Defining an array


#### Import NumPy as np

In [0]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.array([0,0,0,0,0,0,0,0,0,0])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [4]:
np.array([1,1,1,1,1,1,1,1,1,1])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Create an array of 10 tens

In [5]:
np.array([10,10,10,10,10,10,10,10,10,10])


array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

#### Create an array of the integers from 10 to 100

In [0]:
np.arange(10, 101, 1)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### Create an array of all the odd integers from 10 to 30

In [0]:
np.arange(11, 30 , 2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

#### Create a 3x3 array with values ranging from 0 to 8 

In [0]:
a = np.array([0,1,2,3,4,5,6,7,8])
a.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create an array of 25 random numbers between 0 and 1

In [0]:
np.random.sample(25) *1

array([0.4747079 , 0.12786758, 0.52523033, 0.22372279, 0.72894273,
       0.11992174, 0.05089637, 0.14021239, 0.17503603, 0.94375881,
       0.73789566, 0.19951687, 0.01713538, 0.18661925, 0.06499484,
       0.08809836, 0.59667769, 0.18560157, 0.95438616, 0.40516222,
       0.97602977, 0.77528226, 0.51125523, 0.51315617, 0.90069192])

#### Create an array of 40 linearly spaced points between 0 and 10:

In [0]:
np.linspace(1,10,40)

array([ 1.        ,  1.23076923,  1.46153846,  1.69230769,  1.92307692,
        2.15384615,  2.38461538,  2.61538462,  2.84615385,  3.07692308,
        3.30769231,  3.53846154,  3.76923077,  4.        ,  4.23076923,
        4.46153846,  4.69230769,  4.92307692,  5.15384615,  5.38461538,
        5.61538462,  5.84615385,  6.07692308,  6.30769231,  6.53846154,
        6.76923077,  7.        ,  7.23076923,  7.46153846,  7.69230769,
        7.92307692,  8.15384615,  8.38461538,  8.61538462,  8.84615385,
        9.07692308,  9.30769231,  9.53846154,  9.76923077, 10.        ])

## Indexing 


In [0]:
#You are given the following 2D array
a = np.arange(1,25).reshape(4,-1)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [0]:
# Use array indexing to select the subset that contains 9,10,11,12,15,16,17,18,21,22,23,24. 
# In other words, the 3 * 4 sub-matrix in the bottom right corner of your array
# I have shown you the output -- be careful, if you run your code, it is going to "wipe out" my output
a2 = np.delete(np.delete(a,0,0), [0,1], 1)
a2

array([[ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24]])

In [0]:
# Use array indexing  get the value 20, as my output shows
a[3][1]

20

In [0]:
# Use array indexing  get the column 10, 16, 22, as my output shows
a2[:,[1]]

array([[10],
       [16],
       [22]])

In [0]:
# Use array indexing  get the row [15,16,17] as my output shows
a2[[1],:3]

array([[15, 16, 17]])

### Now the hard task!

#### Write a function that gives the users four random integers between 1 and 10 and ask them to enter the square number of them. If the user answers all of them correctly, congratulate them. Otherwise, show them the right answer

In [0]:
# Step 0: Import numpy -- ALWAYS import all the libraries you need at the beginning!
import numpy as np

#Step 1: Function creation -- refer to the last lab for the syntax of function creation
# does our function take parameters?
# Create your function here:

    
#Step 2: Create an array of four random integers between 1 and 10 
   
#Step 3: Print your numbers


#Step 4: Prompt the user to enter four numbers, ONE AT A TIME. Use a loop to store these four numbers in a new array
#  HINT 1: We could take all four numbers in through one line, but to practice loop, let's do it the hard way
#  HINT 2: You can start by creating an empty array -- np.array([]), then appending to it one at a time
#  HINT 3: Remember, input() only returns STRINGS. You need to turn them into integers














#Step 5: Now that you have the two arrays, you can compare them using array functions and decide whether the answers are correct
#  HINT 4: To compare two arrays, you can use array1 == array2 -- however, you have to use a variable to hold the result
#          The resulted array is an array of Boolean values. To quickly check whether it contains true value, you might want to
#          use the all() or any() function...





    